### ISSUE TITLE
As a user, I can view a list of tasks at a specific day

### ISSUE THREAD

**Issue by WongKinFei** [cs2103jan2015-t13-3j/main#10]
so that I can have a clearer view of my tasks in a particular day. (Eg, today)

ID: viewByDay

**Comment by TimothyTam** [comment]
closed. Same as the other issue (#16)

**Comment by TimothyTam** [comment]
Also, at start, "today" will be displayed, can use command to show others.

**Comment by TimothyTam** [comment]
im pretty sure this is done. closing again.
