### ISSUE TITLE
Refactoring of code (Round 1)

### ISSUE THREAD

**Issue by TimothyTam** [cs2103jan2015-t13-3j/main#27]
1) refactor project name to actual project name as discussed.
2) refactor code to match architecture diagram (UI, Logic, Parser, Data Storage).
3) refactor code to match sequence diagram.
4) refactor package name.
5) refactor all naming of variable, methods, parameters and classes to be natural language readable.
6) check that all java convention are matched, SLAP is applied and OOP is there.

**Comment by WongKinFei** [comment]
I will be doing this.

**Comment by C-YanHua** [comment]
as of current the project is not OOP, rather everything is concentrated in the MainApp.java. The code is not segregated into the individual components. SLAP is almost non-existence...so we need to refactor quite abit.

**Comment by C-YanHua** [comment]
Code refactored. Still require significant modification but is good enough for round 1 refactoring.
