### ISSUE TITLE
Should the return value be Integer for all the methods?

### ISSUE THREAD

**Issue by WongKinFei** [cs2103jan2015-t13-3j/main#29]
The current implementation utilize command code or success/failure code as a return value. Are we implementing a proper command code mapping to its respective error message or what is the main purpose of the command code? Should we instead return the error message itself for readability and reduce redundancy?

**Comment by C-YanHua** [comment]
change implementation. return boolean instead. if true, view will get successMessage from controller else view will get errorMessage from controller
