### ISSUE TITLE
Should we apply singleton pattern for CommandParser/Validator and use the object? 

### ISSUE THREAD

**Issue by TimothyTam** [cs2103jan2015-t13-3j/main#34]
ADD COMMENT

**Comment by TimothyTam** [comment]
Basic GUI is up.

**Comment by LeeWeiHong** [comment]
So when i first did the parser and validator, didn't know of the singleton pattern and used static for the methods. Now that i saw webcast, i'm thinking maybe can change to singleton pattern and initialize the object in commandcontroller.

**Comment by C-YanHua** [comment]
Might want to consider looking at a few websites below that shows the different usage and why people choose static classes or singleton pattern for their implementation before we decide what we want to use.

http://stackoverflow.com/questions/519520/difference-between-static-class-and-singleton-pattern
http://javarevisited.blogspot.sg/2013/03/difference-between-singleton-pattern-vs-static-class-java.html

**Comment by LeeWeiHong** [comment]
One benefit for singleton pattern is that it follows OOP and we can initialize it once in controller. At least either method is trivial to implement so can take time to decide.
