### ISSUE TITLE
Changes of DateTime usage

### ISSUE THREAD

**Issue by LeeWeiHong** [cs2103jan2015-t13-3j/main#35]
The OLD method of DateTime uses setDate for both startDateTime and endDateTime.
There is a flaw in method.

Eg. from 13/3 4pm to 13/3 6pm (13/3 is repeated, not user friendly)
However setDate("13/3 4pm") and setDate("13/3 6pm") works.

If user enters "from 13/3 4pm to 6pm" then setDate("6pm") fails.

New method:
setEndDate("6pm", startDate) (here startDate is done using setDate and required for checking)
If user enters "13/3 4pm to 14/4 6pm" then endDate = "14/4 6pm" else
user enters "13/3 4pm to 6pm" then endDate = "13/3 6pm"

**Comment by C-YanHua** [comment]
interesting. Let us discuss further on thursday meet up.

**Comment by C-YanHua** [comment]
enhancement accepted.
