### ISSUE TITLE
Issue with changing task to floating/deadline task for edit function

### ISSUE THREAD

**Issue by C-YanHua** [cs2103jan2015-t13-3j/main#36]
Kin fei have mentioned that as of current, the user is not able to change the type of the task through edit. For example: a task is already specify as a normal task. However, due to a flaw in the design of our edit command, the user can't specific any field to convert the normal task to a floating task.

**Comment by LeeWeiHong** [comment]
I was thinking converting of normal task to floating task/deadline task can make of use of reset() in DateTime, which i just included. reset() is just like new DateTime() except it does not create a new DateTime().

So perhaps Task can have a simple method like
toFloatingTask() { startDateTime.reset(); endDateTime.reset(); }
toDeadlineTask() {startDateTime.reset(); }

**Comment by C-YanHua** [comment]
kin fei take note of this please

**Comment by TimothyTam** [comment]
kf has done it, well done, close.
