### ISSUE TITLE
BUG IN DATE PARSING FOR COMMANDPARSER

### ISSUE THREAD

**Issue by C-YanHua** [cs2103jan2015-t13-3j/main#41]
I found a bug in the following method:
getStartDateTime
getEndDateTime

let say if i were to enter the following command:
edit 4 from 1/4 to 3/4, the regex would actually catch the '4' in 1/4 and strip it away for some reason.
so the output will become 1/'blank'
if i were to type:
edit 4 from 1/5 to 3/5, it will work! PLEASE FIX!!! =)
(i think this will only occur for commands that utilize indexing)

**Comment by LeeWeiHong** [comment]
This isn't a bug on my side.. lol..
The getEditCmdParameters in CommandParser.java, line 81:
command = removeFirstWord(command); ---> for edit 4 from 1/4 to 3/4
You're doing removeFirstWord("4") ---> this replace all the 4 with "" that's why you get 1/blank instead of 1/4.. ):

**Comment by LeeWeiHong** [comment]
I included the testing in ParserTest for edit 4 from 1/4 to 3/4.
What i can suggest is to avoid removing and just get the information straight away, the regex is good enough to handle it

**Comment by C-YanHua** [comment]
o oops sorry didn't know. i will see what i can do

**Comment by C-YanHua** [comment]
Bug fixed. Thanks Wei Hong ~.~

**Comment by LeeWeiHong** [comment]
Yeah. I test in ParserTest. add 'add task' --> removeFirstWord gives ' task'.. lol

**Comment by C-YanHua** [comment]
go school liaox late for lesson ~.~ thanks for help hahahaha
