### ISSUE TITLE
Regarding HashMap in command parser

### ISSUE THREAD

**Issue by LeeWeiHong** [cs2103jan2015-t13-3j/main#42]
Refactoring 
CommandTypes evaluateCommand into
HashMap<CmdParameters, Object> evaluateCommand only allows edit to work, add/remove/mark/view currently all not working.

There are changes needed to fill up all the HashMap methods in CommandParser. I feel that this is like shifting the work from each invididual Add/Edit/../View class into CommandParser just to adopt the HashMap method. I feel this defeats the purpose of having the command class because so much work is done in the CommandParser it feels like when we are doing everything in controller..

Also the HashMap requires object casting since we have strings, arraylist as parameters.

But actually i having fully understand the HashMap edit method so i don't think i can modify add to work by tomorrow. ): So for now i will keep at previous version where all the commands are still working. I think we can discuss about how is our implementation is really going to be tomorrow since most of our features are done.

**Comment by C-YanHua** [comment]
Your previous version command should still work as per norm. I ensured that the new implementation will not affect the old 1. 

If yours is not working, drop me a note, i will see what is wrong. ~.~

**Comment by LeeWeiHong** [comment]
Okay.
