### ISSUE TITLE
Something wrong with the setDate sia omg

### ISSUE THREAD

**Issue by TimothyTam** [cs2103jan2015-t13-3j/main#44]
03/04 doesnt work. Should that be valid?! should that not be valid?!

I think it will work if d/M was changed to dd/MM, but should it be valid or not valid. 

Do we want 0x/0x to be valid or not? That is the question!

**Comment by LeeWeiHong** [comment]
I know easy fix. I tell you all later.

**Comment by TimothyTam** [comment]
k
