### ISSUE TITLE
splitTags method regex exception case

### ISSUE THREAD

**Issue by LeeWeiHong** [cs2103jan2015-t13-3j/main#45]
If we choose to allow multiple hashtags sperated by whitespaces then there is an exception case for splitTags regex.
E.g. #hashtag1 #hashtag2 from start to end results in:
#hashtag1 and
#hashtag2 from start to end

Maybe want to check for edit hashtags because something like #hashtag1 #hashtag2 garbage text will give you a second hashtag of "#hashtag2 garbage text".

For now i have refactor getTags into setTags because i needed a method getTags for add commands.
E.g. #hashtag1 #hashtag2 from start to end, i assume that if user wants to add hashtags then it must come before from start datetime. Then i would retrieve hashtags before "from start datetime". Then proceed to setTags with the retrieved information.

But i still don't know how to tackle #hashtag2 garbage text. Do we assume this is a user problem or do we process" #<hashtag1> #<hashtag2> garbage text (ignored)" and ignore after whitespace (tried to write a regex for this and failed) or do we revert to old way of not allowing whitespaces (#hashtag1#hashtag2..#hashtagINF)?

**Comment by C-YanHua** [comment]
i guess if we really have no way to catch the garbage text due to the spaces, than we can just stick with the old implementation whereby the tags must be stick together without any whitespaces. #hashtag1#hashtag2

**Comment by TimothyTam** [comment]
???
"#tag garbage", why can't that be the entire tag?? maybe he want a tag with whitespace. 

isn't it 
add 'task' from xx to xx every xx #whatever #anything garbage

**Comment by LeeWeiHong** [comment]
Yup. Then it will fall under user problem. If user wants to have a hashtag 'garbage' that is his choice. But do we want to protect such a user is the problem.

**Comment by TimothyTam** [comment]
i guess follow common convention that tags dont have whitespace lor, so if "#any garbage" the command will fail??

**Comment by LeeWeiHong** [comment]
I wanted to tried that. I couldn't write up the regex though.. lol

**Comment by TimothyTam** [comment]
cant regex then just remove everything after # the regex the remaining one ba, regex is actually extremely expensive

**Comment by LeeWeiHong** [comment]
I managed a fix for hastag. Refer to getTags and removeTags methods in CommandParser.
Basic idea: assumption of #hashtag cannot have white spaces
Eg. #hashtag1 = #hashtag1, #hashtag1 hashtag2 = #hashtag1.
It is too hard to satisfy all the cases for hashtag with spaces. No idea where to stop.

A command like this:
add 'normal 1' #hashtag1 from 5/4 #hashtag2 to 6/4 #hashtag3 for #hashtag4  2 week
would still work now.

**Comment by TimothyTam** [comment]
WH has done it.

Now tag cannot have whitespaces in between.
