### ISSUE TITLE
As a user, I can add a task by specifying only the task description

### ISSUE THREAD

**Issue by C-YanHua** [cs2103jan2015-t13-3j/main#6]
record tasks that are non-critical and have no impact on my schedule.

ID: addFloatingTask

**Comment by LeeWeiHong** [comment]
Partially done, currently supported command: "add 'task' " (assigned as floating task)
Need to be work on is adding floating task with tags (command not supported yet)

**Comment by LeeWeiHong** [comment]
Implemented with supported command: add 'task' or add 'task' #tags1
