### ISSUE TITLE
As a user, I can add a task by specifying a task description and the parameters for a recurring task

### ISSUE THREAD

**Issue by C-YanHua** [cs2103jan2015-t13-3j/main#7]
so that I can record tasks that I need to complete every particular day or every certain datetime interval (every 2 days, every Monday, …).

ID: addRecurringTask

**Comment by LeeWeiHong** [comment]
Recurring task considered completed.
List of supported command:
add 'recurring task 1' today 4pm to 6pm for 5 week
add 'recurring task 2' tmr 4pm to 6pm for 2 week except 1
add 'recurring task 3' tmr 4pm to 6pm for 5 week except 3, 5
add 'recurring task 4' today 4pm to 6pm every week
add 'recurring task 5' today 4pm to 6pm every 2 week
add 'recurring task 6' today 4pm to 6pm every week except 7
